### ISSUE TITLE
메일 테스트 이슈

### ISSUE THREAD

**Issue by insanehong** [semtlnori/nori#10]

**Comment by insanehong** [comment]
여기에 이미지를 첨부해서 답변주세요

**Comment by insanehong** [comment]
@semtlnori @npcode  요기임

**Comment by eungjun-yi** [comment]
이미지 테스트

2014-09-25 18:28 GMT+09:00 insanehong notifications@github.com:

**Comment by insanehong** [comment]
이미지 삽입

2014-09-25 18:29 GMT+09:00 Yi EungJun notifications@github.com:

> 이미지 테스트
> 
> 2014-09-25 18:28 GMT+09:00 insanehong notifications@github.com:
> 
> > @semtlnori https://github.com/semtlnori @npcode
> > https://github.com/npcode 요기임
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/semtlnori/nori/issues/10#issuecomment-56794702.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/semtlnori/nori/issues/10#issuecomment-56794815.

## 

/*
- @insanehong
  *
- @Name DeokHong Kim
- @Desc Web Developer, Front-end Engineer at NAVER Corp.
- @Twitter @insanehong http://twitter.com/insanehong
- @Blog incorrect note http://insanehong.kr/
- @Return insanehong@gmail.com
- @Aboutme : http://about.me/insanehong
  */

**Comment by insanehong** [comment]
에이 얘네도 뭐 그닥이네
